[package]
name = "nyuka-packaging"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
nyuka-domain = { path = "../domain" }
async-trait = { workspace = true }
chrono = { workspace = true }
quick-xml = { workspace = true }
rustix = { workspace = true }
unicode-normalization = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
zip = { workspace = true }
tempfile = { workspace = true }
