[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nyuka-api = { path = "../crates/api" }
nyuka-aidoku-runtime = { path = "../crates/aidoku-runtime" }
reqwest = { workspace = true, features = ["blocking"] }
serde = { workspace = true }
url = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
