//! SeaORM entities.
//!
//! Generated by `sea-orm-cli generate entity` and committed. The CI drift
//! check regenerates these against a migrated ephemeral database and fails on
//! any diff — that check is what substitutes for compile-time SQL
//! verification (ADR-0002).
