//! Migrations, defined programmatically so they are embedded in the binary
//! and callable at boot.
//!
//! Note for the first migration (ADR-0002): SeaORM 2.0 emits
//! `GENERATED BY DEFAULT AS IDENTITY` rather than `serial` for PostgreSQL
//! auto-increment columns.
//!
//! The `job` table needs a partial index on `(priority, run_at)` restricted to
//! `state = 'queued'`, and lowered `autovacuum_vacuum_scale_factor`, or claim
//! latency drifts upward as terminal rows accumulate (ADR-0003).
