//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "chapter")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "idx_chapter_manga_external")]
    pub manga_id: Uuid,
    #[sea_orm(unique_key = "idx_chapter_manga_external")]
    pub external_key: String,
    pub title: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub number: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub volume: Option<f32>,
    pub published_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary")]
    pub scanlators: Json,
    pub url: Option<String>,
    pub language: Option<String>,
    pub locked: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::downloaded_chapter::Entity")]
    DownloadedChapter,
    #[sea_orm(
        belongs_to = "super::manga::Entity",
        from = "Column::MangaId",
        to = "super::manga::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Manga,
}

impl Related<super::downloaded_chapter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DownloadedChapter.def()
    }
}

impl Related<super::manga::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Manga.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
