//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod app_user;
pub mod chapter;
pub mod downloaded_chapter;
pub mod follow;
pub mod job;
pub mod manga;
pub mod session;
pub mod source;
pub mod source_kv;
pub mod source_repo;
