//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "source")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "idx_source_repo_external")]
    pub repo_id: Uuid,
    #[sea_orm(unique_key = "idx_source_repo_external")]
    pub external_id: String,
    pub name: String,
    pub version: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub languages: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub required_capabilities: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub declared_rate_limit: Option<Json>,
    pub installed_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::manga::Entity")]
    Manga,
    #[sea_orm(has_many = "super::source_kv::Entity")]
    SourceKv,
    #[sea_orm(
        belongs_to = "super::source_repo::Entity",
        from = "Column::RepoId",
        to = "super::source_repo::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SourceRepo,
}

impl Related<super::manga::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Manga.def()
    }
}

impl Related<super::source_kv::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SourceKv.def()
    }
}

impl Related<super::source_repo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SourceRepo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
