//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "source_repo_entry")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub repo_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub external_id: String,
    pub name: String,
    pub version: i32,
    pub icon_url: Option<String>,
    pub download_url: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub languages: Json,
    pub content_rating: i16,
    pub base_url: Option<String>,
    pub min_app_version: Option<String>,
    pub fetched_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::source_repo::Entity",
        from = "Column::RepoId",
        to = "super::source_repo::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SourceRepo,
}

impl Related<super::source_repo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SourceRepo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
