//! Migrations, defined programmatically so they are embedded in the binary and
//! callable at boot.
//!
//! Two notes that apply to every migration here:
//!
//! - SeaORM 2.0 emits `GENERATED BY DEFAULT AS IDENTITY` rather than `serial`
//!   for auto-increment columns. This schema uses UUID keys throughout, so it
//!   does not come up, but it will if an integer key is ever added.
//! - `user` is a reserved word in PostgreSQL. The table is `app_user` so that
//!   every query does not have to quote it, which is the kind of thing that
//!   gets forgotten in exactly one place.

pub use sea_orm_migration::prelude::*;

mod m0001_initial;
mod m0002_source_repo_entry;

pub struct Migrator;

#[async_trait::async_trait]
impl MigratorTrait for Migrator {
    fn migrations() -> Vec<Box<dyn MigrationTrait>> {
        vec![
            Box::new(m0001_initial::Migration),
            Box::new(m0002_source_repo_entry::Migration),
        ]
    }
}
