/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chapters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/chapters/{id}` */
        get: operations["chapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /api/v1/downloads`
         * @description Returns `202` with a `Location` pointing at the job. The work is a series
         *     of requests to a third-party site; doing it inline would hold a connection
         *     open for minutes.
         *
         *     Idempotent on the chapter, so a double-click queues one download. An
         *     `Idempotency-Key` header is accepted and narrows that further, which is
         *     what makes a retried request from a flaky network safe.
         */
        post: operations["request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/downloads/{chapter_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/downloads/{chapter_id}/file` */
        get: operations["file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/follows` */
        get: operations["list"];
        /**
         * `PUT /api/v1/follows` — follow a series, or change how it is followed.
         * @description `PUT` rather than `POST` because the operation is keyed on `manga_id` and
         *     is idempotent: following an already-followed series updates it instead of
         *     creating a second follow, which is what a user pressing the button twice
         *     expects.
         */
        put: operations["upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/follows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/follows/{id}` */
        get: operations["get"];
        put?: never;
        post?: never;
        /** `DELETE /api/v1/follows/{id}` */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/follows/{id}/check-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/follows/{id}/check-now` */
        post: operations["check_now"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/jobs` */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/jobs/{id}` */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /api/v1/jobs/{id}/cancel`
         * @description Cancelling a `running` job stops it from being retried; it does not
         *     interrupt the attempt in flight. That is an honest limit rather than an
         *     oversight — see ADR-0003's open question on cancellation semantics.
         */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/jobs/{id}/retry` */
        post: operations["retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manga": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/manga` */
        get: operations["list"];
        put?: never;
        /**
         * `POST /api/v1/manga` — add a catalog entry to the library.
         * @description The body names a source and a key, not a series: the metadata comes from
         *     the source, never from the client. Accepting a client's version would let
         *     anyone write any title into the library.
         */
        post: operations["add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manga/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/manga/{id}` */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manga/{id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/manga/{id}/chapters` */
        get: operations["chapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/source-repos` */
        get: operations["list_repos"];
        put?: never;
        /** `POST /api/v1/source-repos` */
        post: operations["add_repo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-repos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** `DELETE /api/v1/source-repos/{id}` */
        delete: operations["delete_repo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-repos/{id}/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/source-repos/{id}/available` */
        get: operations["available"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-repos/{id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/source-repos/{id}/refresh` */
        post: operations["refresh_repo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/sources` */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * `DELETE /api/v1/sources/{id}`
         * @description > [!WARNING]
         *     > This cascades. Every series from this source and everything hanging off
         *     > them is removed from the database. Packaged files in the library are left
         *     > alone — they are the user's — but nothing will know how to find them
         *     > again.
         */
        delete: operations["uninstall"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/sources/{id}/catalog` */
        get: operations["browse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}/catalog/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/sources/{id}/catalog/{key}` */
        get: operations["details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}/catalog/{key}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/sources/{id}/catalog/{key}/chapters` */
        get: operations["chapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/sources/{id}/filters` */
        get: operations["filters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddRequest: {
            external_key: string;
            /** Format: uuid */
            source_id: string;
        };
        /** @description A catalog result, which has no local identity. */
        CatalogItemDto: {
            artists: string[];
            authors: string[];
            content_rating: string;
            cover_url?: string | null;
            description?: string | null;
            /** @description The source's own key. This, plus the source id, is how it is added. */
            external_key: string;
            /**
             * Format: uuid
             * @description Set when this series is already in the library, so the UI can offer
             *     "open" rather than "add".
             */
            manga_id?: string | null;
            reading_direction: string;
            status: string;
            tags: string[];
            title: string;
            url?: string | null;
        };
        CatalogPage: {
            items: components["schemas"]["CatalogItemDto"][];
            next_cursor?: string | null;
        };
        ChapterDto: {
            external_key: string;
            /** Format: uuid */
            id: string;
            language?: string | null;
            /** Format: uuid */
            manga_id: string;
            /** Format: float */
            number?: number | null;
            /** Format: date-time */
            published_at?: string | null;
            title?: string | null;
            /** Format: float */
            volume?: number | null;
        };
        DownloadRequest: {
            /** Format: uuid */
            chapter_id: string;
        };
        FollowDto: {
            auto_download: boolean;
            /** Format: int32 */
            check_interval_secs: number;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_checked_at?: string | null;
            /** Format: uuid */
            manga_id: string;
        };
        FollowRequest: {
            auto_download?: boolean;
            /**
             * Format: int32
             * @description Defaults to six hours when absent.
             */
            check_interval_secs?: number | null;
            /** Format: uuid */
            manga_id: string;
        };
        InstalledSourceDto: {
            declared_rate_limit?: null | components["schemas"]["RateLimitDto"];
            external_id: string;
            /** Format: uuid */
            id: string;
            languages: string[];
            name: string;
            /** Format: uuid */
            repo_id: string;
            required_capabilities: string[];
            /** Format: int32 */
            version: number;
        };
        JobDto: {
            /** Format: int32 */
            attempts: number;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            kind: string;
            last_error?: string | null;
            /** Format: int32 */
            max_attempts: number;
            /** Format: int32 */
            priority: number;
            /** Format: date-time */
            run_at: string;
            state: string;
        };
        MangaDto: {
            artists: string[];
            authors: string[];
            content_rating: string;
            cover_url?: string | null;
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            external_key: string;
            /** Format: uuid */
            id: string;
            language?: string | null;
            reading_direction: string;
            /** Format: uuid */
            source_id: string;
            status: string;
            tags: string[];
            title: string;
            /** Format: date-time */
            updated_at: string;
            url?: string | null;
        };
        /**
         * @description One page of results.
         *
         *     `next_cursor` is opaque and is the only supported way to ask for the next
         *     page. Offsets are deliberately absent: they shift under inserts, and a
         *     library that gains a chapter mid-scroll would skip or repeat one.
         */
        Paged_ChapterDto: {
            items: {
                external_key: string;
                /** Format: uuid */
                id: string;
                language?: string | null;
                /** Format: uuid */
                manga_id: string;
                /** Format: float */
                number?: number | null;
                /** Format: date-time */
                published_at?: string | null;
                title?: string | null;
                /** Format: float */
                volume?: number | null;
            }[];
            next_cursor?: string | null;
        };
        /**
         * @description One page of results.
         *
         *     `next_cursor` is opaque and is the only supported way to ask for the next
         *     page. Offsets are deliberately absent: they shift under inserts, and a
         *     library that gains a chapter mid-scroll would skip or repeat one.
         */
        Paged_FollowDto: {
            items: {
                auto_download: boolean;
                /** Format: int32 */
                check_interval_secs: number;
                /** Format: date-time */
                created_at: string;
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                last_checked_at?: string | null;
                /** Format: uuid */
                manga_id: string;
            }[];
            next_cursor?: string | null;
        };
        /**
         * @description One page of results.
         *
         *     `next_cursor` is opaque and is the only supported way to ask for the next
         *     page. Offsets are deliberately absent: they shift under inserts, and a
         *     library that gains a chapter mid-scroll would skip or repeat one.
         */
        Paged_JobDto: {
            items: {
                /** Format: int32 */
                attempts: number;
                /** Format: date-time */
                created_at: string;
                /** Format: uuid */
                id: string;
                kind: string;
                last_error?: string | null;
                /** Format: int32 */
                max_attempts: number;
                /** Format: int32 */
                priority: number;
                /** Format: date-time */
                run_at: string;
                state: string;
            }[];
            next_cursor?: string | null;
        };
        /**
         * @description One page of results.
         *
         *     `next_cursor` is opaque and is the only supported way to ask for the next
         *     page. Offsets are deliberately absent: they shift under inserts, and a
         *     library that gains a chapter mid-scroll would skip or repeat one.
         */
        Paged_MangaDto: {
            items: {
                artists: string[];
                authors: string[];
                content_rating: string;
                cover_url?: string | null;
                /** Format: date-time */
                created_at: string;
                description?: string | null;
                external_key: string;
                /** Format: uuid */
                id: string;
                language?: string | null;
                reading_direction: string;
                /** Format: uuid */
                source_id: string;
                status: string;
                tags: string[];
                title: string;
                /** Format: date-time */
                updated_at: string;
                url?: string | null;
            }[];
            next_cursor?: string | null;
        };
        RateLimitDto: {
            /** Format: int32 */
            period_seconds: number;
            /** Format: int32 */
            permits: number;
        };
        SourceEntryDto: {
            base_url?: string | null;
            content_rating: string;
            external_id: string;
            icon_url?: string | null;
            /**
             * Format: int32
             * @description Absent when the entry is not installed.
             */
            installed_version?: number | null;
            languages: string[];
            name: string;
            /** Format: uuid */
            repo_id: string;
            /** Format: int32 */
            version: number;
        };
        SourceRepoDto: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_refreshed_at?: string | null;
            name: string;
            url: string;
        };
        SourceRepoRequest: {
            name: string;
            /** @description The index URL, such as `https://example.test/index.min.json`. */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chapter id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterDto"];
                };
            };
            /** @description No such chapter */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    request: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadRequest"];
            };
        };
        responses: {
            /** @description Queued; `Location` names the job */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such chapter */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already in the library */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chapter id */
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The CBZ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.comicbook+zip": unknown;
                };
            };
            /** @description The requested range */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The ETag matched */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not downloaded */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The range is outside the file */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description The `next_cursor` from a previous page. */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_FollowDto"];
                };
            };
        };
    };
    upsert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowDto"];
                };
            };
            /** @description Invalid interval */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such series */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Follow id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowDto"];
                };
            };
            /** @description No such follow */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Follow id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed, or already absent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    check_now: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Follow id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A check was queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such follow */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description One of `queued`, `running`, `succeeded`, `failed`, `cancelled`. */
                state?: string | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_JobDto"];
                };
            };
            /** @description Unknown state filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDto"];
                };
            };
            /** @description No such job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDto"];
                };
            };
            /** @description No such job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The job has already finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued again */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The job has not finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description The `next_cursor` from a previous page. */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_MangaDto"];
                };
            };
        };
    };
    add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRequest"];
            };
        };
        responses: {
            /** @description Added, or already present */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MangaDto"];
                };
            };
            /** @description No such source or series */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The source could not be reached */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MangaDto"];
                };
            };
            /** @description No such series */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chapters: {
        parameters: {
            query?: {
                /** @description The `next_cursor` from a previous page. */
                cursor?: string | null;
            };
            header?: never;
            path: {
                /** @description Series id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_ChapterDto"];
                };
            };
            /** @description No such series */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_repos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRepoDto"][];
                };
            };
        };
    };
    add_repo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRepoRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRepoDto"];
                };
            };
            /** @description Invalid URL */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_repo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Repository id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed, or already absent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    available: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Repository id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceEntryDto"][];
                };
            };
            /** @description No such repository */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_repo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Repository id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A refresh was queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such repository */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstalledSourceDto"][];
                };
            };
        };
    };
    uninstall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed, or already absent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    browse: {
        parameters: {
            query?: {
                /** @description Free-text search. Absent means the source's default listing. */
                q?: string | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                /** @description Source id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogPage"];
                };
            };
            /** @description No such source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The source could not be reached */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    details: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source id */
                id: string;
                /** @description The source's own key for the series */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogItemDto"];
                };
            };
            /** @description No such source or series */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The source could not be reached */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chapters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source id */
                id: string;
                /** @description The source's own key for the series */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterDto"][];
                };
            };
            /** @description No such source or series */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The source could not be reached */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    filters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The source's filter definitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No such source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
