/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chapters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/chapters/{id}` */
        get: operations["getChapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /api/v1/downloads`
         * @description Returns `202` with a `Location` pointing at the job. The work is a series
         *     of requests to a third-party site; doing it inline would hold a connection
         *     open for minutes.
         *
         *     Idempotent on the chapter, so a double-click queues one download. An
         *     `Idempotency-Key` header is accepted and narrows that further, which is
         *     what makes a retried request from a flaky network safe.
         */
        post: operations["requestDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/downloads/{chapter_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/downloads/{chapter_id}/file` */
        get: operations["getChapterFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/follows` */
        get: operations["listFollows"];
        /**
         * `PUT /api/v1/follows` — follow a series, or change how it is followed.
         * @description `PUT` rather than `POST` because the operation is keyed on `manga_id` and
         *     is idempotent: following an already-followed series updates it instead of
         *     creating a second follow, which is what a user pressing the button twice
         *     expects.
         */
        put: operations["upsertFollow"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/follows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/follows/{id}` */
        get: operations["getFollow"];
        put?: never;
        post?: never;
        /** `DELETE /api/v1/follows/{id}` */
        delete: operations["deleteFollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/follows/{id}/check-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/follows/{id}/check-now` */
        post: operations["checkFollowNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/jobs` */
        get: operations["listJobs"];
        put?: never;
        /**
         * `POST /api/v1/jobs` — queue a maintenance job.
         * @description Exists because the alternative is a runbook that tells an operator to
         *     `INSERT` into the `job` table. A documented raw insert is a schema
         *     dependency in prose: it survives exactly until a column changes, and it
         *     bypasses every validation the enqueue path performs.
         */
        post: operations["triggerJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/jobs/{id}` */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /api/v1/jobs/{id}/cancel`
         * @description Cancelling a `running` job stops it from being retried; it does not
         *     interrupt the attempt in flight. That is an honest limit rather than an
         *     oversight — see ADR-0003's open question on cancellation semantics.
         */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/jobs/{id}/retry` */
        post: operations["retryJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manga": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/manga` */
        get: operations["listLibrary"];
        put?: never;
        /**
         * `POST /api/v1/manga` — add a catalog entry to the library.
         * @description The body names a source and a key, not a series: the metadata comes from
         *     the source, never from the client. Accepting a client's version would let
         *     anyone write any title into the library.
         */
        post: operations["addMangaToLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manga/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/manga/{id}` */
        get: operations["getManga"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manga/{id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/manga/{id}/chapters` */
        get: operations["listMangaChapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/source-repos` */
        get: operations["listSourceRepos"];
        put?: never;
        /** `POST /api/v1/source-repos` */
        post: operations["addSourceRepo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-repos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** `DELETE /api/v1/source-repos/{id}` */
        delete: operations["deleteSourceRepo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-repos/{id}/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/source-repos/{id}/available` */
        get: operations["listAvailableSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-repos/{id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/source-repos/{id}/refresh` */
        post: operations["refreshSourceRepo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/sources` */
        get: operations["listSources"];
        put?: never;
        /**
         * `POST /api/v1/sources` — install from a repository entry.
         * @description Synchronous rather than a job. The client is waiting to use the source, the
         *     work is one download and one compile, and the capability refusal has to
         *     reach the person who pressed install — a failed job they have to go and
         *     read reports a host gap as though it were a site problem, which ADR-0004
         *     names as the worst outcome.
         */
        post: operations["installSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * `DELETE /api/v1/sources/{id}`
         * @description > [!WARNING]
         *     > This cascades. Every series from this source and everything hanging off
         *     > them is removed from the database. Packaged files in the library are left
         *     > alone — they are the user's — but nothing will know how to find them
         *     > again.
         */
        delete: operations["uninstallSource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/sources/{id}/catalog` */
        get: operations["browseCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}/catalog/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/sources/{id}/catalog/{key}` */
        get: operations["getCatalogItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}/catalog/{key}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/sources/{id}/catalog/{key}/chapters` */
        get: operations["listCatalogChapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/sources/{id}/filters` */
        get: operations["getSourceFilters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/sources/{id}/settings`
         * @description # Values are opaque, and that is not laziness
         *
         *     A source's settings are read and written by its WASM module through the
         *     `defaults` host import, which postcard-encodes them. This server does not
         *     know what a given key means to a given source — the shape is declared in
         *     the package's `settings.json` and interpreted by the module.
         *
         *     So values go over the wire base64-encoded rather than decoded into JSON.
         *     Decoding would mean this server guessing at a schema it does not have, and
         *     guessing wrong writes a value the source then misreads.
         */
        get: operations["getSourceSettings"];
        /** `PUT /api/v1/sources/{id}/settings` */
        put: operations["putSourceSetting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddRequest: {
            external_key: string;
            /** Format: uuid */
            source_id: string;
        };
        /** @description A catalog result, which has no local identity. */
        CatalogItemDto: {
            artists: string[];
            authors: string[];
            content_rating: string;
            cover_url?: string | null;
            description?: string | null;
            /** @description The source's own key. This, plus the source id, is how it is added. */
            external_key: string;
            /**
             * Format: uuid
             * @description Set when this series is already in the library, so the UI can offer
             *     "open" rather than "add".
             */
            manga_id?: string | null;
            reading_direction: string;
            status: string;
            tags: string[];
            title: string;
            url?: string | null;
        };
        CatalogPage: {
            items: components["schemas"]["CatalogItemDto"][];
            next_cursor?: string | null;
        };
        ChapterDto: {
            external_key: string;
            /** Format: uuid */
            id: string;
            language?: string | null;
            /** Format: uuid */
            manga_id: string;
            /** Format: float */
            number?: number | null;
            /** Format: date-time */
            published_at?: string | null;
            title?: string | null;
            /** Format: float */
            volume?: number | null;
        };
        /** @description A chapter with its local download state. */
        ChapterSummaryDto: components["schemas"]["ChapterDto"] & {
            /** @description True when a packaged file is recorded for this chapter. */
            downloaded: boolean;
            /**
             * Format: int64
             * @description The packaged size, present only when `downloaded`.
             */
            size_bytes?: number | null;
        };
        DownloadRequest: {
            /** Format: uuid */
            chapter_id: string;
        };
        FollowDto: {
            auto_download: boolean;
            /** Format: int32 */
            check_interval_secs: number;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_checked_at?: string | null;
            /** Format: uuid */
            manga_id: string;
        };
        FollowRequest: {
            auto_download?: boolean;
            /**
             * Format: int32
             * @description Defaults to six hours when absent.
             */
            check_interval_secs?: number | null;
            /** Format: uuid */
            manga_id: string;
        };
        /** @description A follow with the series it watches. */
        FollowSummaryDto: components["schemas"]["FollowDto"] & {
            manga_title: string;
            /**
             * Format: int64
             * @description Chapters not yet in the library. What a follow exists to produce.
             */
            missing_count: number;
            source_name: string;
        };
        InstallRequest: {
            /** @description The source's own id, as the repository index lists it. */
            external_id: string;
            /** Format: uuid */
            repo_id: string;
        };
        InstalledSourceDto: {
            declared_rate_limit?: null | components["schemas"]["RateLimitDto"];
            external_id: string;
            /** Format: uuid */
            id: string;
            languages: string[];
            name: string;
            /** Format: uuid */
            repo_id: string;
            required_capabilities: string[];
            /** Format: int32 */
            version: number;
        };
        JobDto: {
            /** Format: int32 */
            attempts: number;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            kind: string;
            last_error?: string | null;
            /** Format: int32 */
            max_attempts: number;
            /** Format: int32 */
            priority: number;
            /** Format: date-time */
            run_at: string;
            state: string;
        };
        /** @description What a job is about, when that can be resolved. */
        JobSubjectDto: {
            /** Format: uuid */
            chapter_id: string;
            /** Format: float */
            chapter_number?: number | null;
            chapter_title?: string | null;
            /** Format: uuid */
            manga_id: string;
            manga_title: string;
        };
        /**
         * @description A job with its subject resolved.
         *
         *     This is why the payload stays unexposed: a client needs to know *which*
         *     chapter a download is for, not the opaque arguments the handler runs on.
         *     Resolving it here answers the question without publishing the rest.
         */
        JobSummaryDto: components["schemas"]["JobDto"] & {
            subject?: null | components["schemas"]["JobSubjectDto"];
        };
        MangaDto: {
            artists: string[];
            authors: string[];
            content_rating: string;
            cover_url?: string | null;
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            external_key: string;
            /** Format: uuid */
            id: string;
            language?: string | null;
            reading_direction: string;
            /** Format: uuid */
            source_id: string;
            status: string;
            tags: string[];
            title: string;
            /** Format: date-time */
            updated_at: string;
            url?: string | null;
        };
        /** @description A library entry with the numbers the list view shows. */
        MangaSummaryDto: components["schemas"]["MangaDto"] & {
            /** Format: int64 */
            chapter_count: number;
            /**
             * Format: int64
             * @description Chapters with a file in the library. The difference from
             *     `chapter_count` is what the progress column shows.
             */
            downloaded_count: number;
            source_name: string;
        };
        /**
         * @description One page of results.
         *
         *     `next_cursor` is opaque and is the only supported way to ask for the next
         *     page. Offsets are deliberately absent: they shift under inserts, and a
         *     library that gains a chapter mid-scroll would skip or repeat one.
         */
        Paged_ChapterSummaryDto: {
            items: (components["schemas"]["ChapterDto"] & {
                /** @description True when a packaged file is recorded for this chapter. */
                downloaded: boolean;
                /**
                 * Format: int64
                 * @description The packaged size, present only when `downloaded`.
                 */
                size_bytes?: number | null;
            })[];
            next_cursor?: string | null;
        };
        /**
         * @description One page of results.
         *
         *     `next_cursor` is opaque and is the only supported way to ask for the next
         *     page. Offsets are deliberately absent: they shift under inserts, and a
         *     library that gains a chapter mid-scroll would skip or repeat one.
         */
        Paged_FollowSummaryDto: {
            items: (components["schemas"]["FollowDto"] & {
                manga_title: string;
                /**
                 * Format: int64
                 * @description Chapters not yet in the library. What a follow exists to produce.
                 */
                missing_count: number;
                source_name: string;
            })[];
            next_cursor?: string | null;
        };
        /**
         * @description One page of results.
         *
         *     `next_cursor` is opaque and is the only supported way to ask for the next
         *     page. Offsets are deliberately absent: they shift under inserts, and a
         *     library that gains a chapter mid-scroll would skip or repeat one.
         */
        Paged_JobSummaryDto: {
            items: (components["schemas"]["JobDto"] & {
                subject?: null | components["schemas"]["JobSubjectDto"];
            })[];
            next_cursor?: string | null;
        };
        /**
         * @description One page of results.
         *
         *     `next_cursor` is opaque and is the only supported way to ask for the next
         *     page. Offsets are deliberately absent: they shift under inserts, and a
         *     library that gains a chapter mid-scroll would skip or repeat one.
         */
        Paged_MangaSummaryDto: {
            items: (components["schemas"]["MangaDto"] & {
                /** Format: int64 */
                chapter_count: number;
                /**
                 * Format: int64
                 * @description Chapters with a file in the library. The difference from
                 *     `chapter_count` is what the progress column shows.
                 */
                downloaded_count: number;
                source_name: string;
            })[];
            next_cursor?: string | null;
        };
        RateLimitDto: {
            /** Format: int32 */
            period_seconds: number;
            /** Format: int32 */
            permits: number;
        };
        SettingRequest: {
            key: string;
            /** @description Base64 of the postcard-encoded value. Absent clears the setting. */
            value?: string | null;
        };
        SourceEntryDto: {
            base_url?: string | null;
            content_rating: string;
            external_id: string;
            icon_url?: string | null;
            /**
             * Format: int32
             * @description Absent when the entry is not installed.
             */
            installed_version?: number | null;
            languages: string[];
            name: string;
            /** Format: uuid */
            repo_id: string;
            /** Format: int32 */
            version: number;
        };
        SourceRepoDto: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_refreshed_at?: string | null;
            name: string;
            url: string;
        };
        SourceRepoRequest: {
            name: string;
            /** @description The index URL, such as `https://example.test/index.min.json`. */
            url: string;
        };
        SourceSettingDto: {
            key: string;
            /** @description Base64 of the postcard-encoded value, or absent when unset. */
            value?: string | null;
        };
        SourceSettingsDto: {
            /**
             * @description The package's `settings.json`, verbatim. A client renders it; this
             *     server does not interpret it.
             */
            declared: unknown;
            /**
             * @description What the source has actually stored, which is not necessarily what the
             *     declaration lists: a source writes keys of its own choosing.
             */
            values: components["schemas"]["SourceSettingDto"][];
        };
        TriggerRequest: {
            /**
             * @description One of `update_sources`, `prune_jobs`, `prune_sessions`,
             *     `reconcile_library`.
             */
            kind: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chapter id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterDto"];
                };
            };
            /** @description No such chapter */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requestDownload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadRequest"];
            };
        };
        responses: {
            /** @description Queued; `Location` names the job */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such chapter */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already in the library */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getChapterFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chapter id */
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The CBZ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.comicbook+zip": unknown;
                };
            };
            /** @description The requested range */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The ETag matched */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not downloaded */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The range is outside the file */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listFollows: {
        parameters: {
            query?: {
                /** @description The `next_cursor` from a previous page. */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_FollowSummaryDto"];
                };
            };
        };
    };
    upsertFollow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowDto"];
                };
            };
            /** @description Invalid interval */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such series */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Follow id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowDto"];
                };
            };
            /** @description No such follow */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteFollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Follow id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed, or already absent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    checkFollowNow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Follow id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A check was queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such follow */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                /** @description One of `queued`, `running`, `succeeded`, `failed`, `cancelled`. */
                state?: string | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_JobSummaryDto"];
                };
            };
            /** @description Unknown state filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    triggerJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerRequest"];
            };
        };
        responses: {
            /** @description Queued; `Location` names the job */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a kind that can be triggered by hand */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummaryDto"];
                };
            };
            /** @description No such job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDto"];
                };
            };
            /** @description No such job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The job has already finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retryJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued again */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The job has not finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listLibrary: {
        parameters: {
            query?: {
                /** @description Free text matched against the title. */
                q?: string | null;
                /** @description One of `unknown`, `ongoing`, `completed`, `cancelled`, `hiatus`. */
                status?: string | null;
                source_id?: string | null;
                /** @description One of `title`, `added`, `updated`, `chapters`. Defaults to `updated`. */
                sort?: string | null;
                /** @description `asc` or `desc`. Defaults to `desc`. */
                dir?: string | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_MangaSummaryDto"];
                };
            };
            /** @description Unknown sort, direction, or status */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addMangaToLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRequest"];
            };
        };
        responses: {
            /** @description Added, or already present */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MangaDto"];
                };
            };
            /** @description No such source or series */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The source could not be reached */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getManga: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MangaDto"];
                };
            };
            /** @description No such series */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMangaChapters: {
        parameters: {
            query?: {
                /** @description The `next_cursor` from a previous page. */
                cursor?: string | null;
            };
            header?: never;
            path: {
                /** @description Series id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_ChapterSummaryDto"];
                };
            };
            /** @description No such series */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSourceRepos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRepoDto"][];
                };
            };
        };
    };
    addSourceRepo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRepoRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRepoDto"];
                };
            };
            /** @description Invalid URL */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSourceRepo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Repository id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed, or already absent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAvailableSources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Repository id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceEntryDto"][];
                };
            };
            /** @description No such repository */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshSourceRepo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Repository id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A refresh was queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such repository */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstalledSourceDto"][];
                };
            };
        };
    };
    installSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstalledSourceDto"];
                };
            };
            /** @description No such repository or entry */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The source needs a capability this build lacks */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The package could not be fetched */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uninstallSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed, or already absent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    browseCatalog: {
        parameters: {
            query?: {
                /** @description Free-text search. Absent means the source's default listing. */
                q?: string | null;
                /**
                 * @description The source's own filters, as a JSON array of filter values.
                 *
                 *     One parameter carrying JSON rather than a parameter per filter. A
                 *     source declares its own filters — 121 of the 136 community sources do
                 *     — so flattening them into the query string would make the shape of a
                 *     request depend on whichever source it was about, and multi-select
                 *     carries separate included and excluded lists that no flat encoding
                 *     holds without inventing a convention.
                 *
                 *     It stays a `GET` so a filtered catalog is a link, which is how every
                 *     screen in this application already keeps its state.
                 *
                 *     Each value is one of:
                 *
                 *     ```json
                 *     [
                 *       {"Text":        {"id": "author", "value": "Mori"}},
                 *       {"Sort":        {"id": "sort", "index": 1, "ascending": false}},
                 *       {"Check":       {"id": "completed", "value": 1}},
                 *       {"Select":      {"id": "status", "value": "ongoing"}},
                 *       {"MultiSelect": {"id": "genre", "included": ["action"], "excluded": ["horror"]}}
                 *     ]
                 *     ```
                 */
                filters?: string | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                /** @description Source id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogPage"];
                };
            };
            /** @description No such source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The source could not be reached */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCatalogItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source id */
                id: string;
                /** @description The source's own key for the series */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogItemDto"];
                };
            };
            /** @description No such source or series */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The source could not be reached */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCatalogChapters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source id */
                id: string;
                /** @description The source's own key for the series */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterDto"][];
                };
            };
            /** @description No such source or series */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The source could not be reached */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSourceFilters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The source's filter definitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No such source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSourceSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSettingsDto"];
                };
            };
            /** @description No such source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putSourceSetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingRequest"];
            };
        };
        responses: {
            /** @description Stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not valid base64, or too large */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
