/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as FollowsRouteImport } from './routes/follows'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BrowseKeyRouteImport } from './routes/browse.$key'
import { Route as DownloadsJobIdRouteImport } from './routes/downloads.$jobId'
import { Route as LibraryMangaIdRouteImport } from './routes/library.$mangaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowsRoute = FollowsRouteImport.update({
  id: '/follows',
  path: '/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseKeyRoute = BrowseKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => BrowseRoute,
} as any)
const DownloadsJobIdRoute = DownloadsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => DownloadsRoute,
} as any)
const LibraryMangaIdRoute = LibraryMangaIdRouteImport.update({
  id: '/$mangaId',
  path: '/$mangaId',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRouteWithChildren
  '/downloads': typeof DownloadsRouteWithChildren
  '/follows': typeof FollowsRoute
  '/library': typeof LibraryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/browse/$key': typeof BrowseKeyRoute
  '/downloads/$jobId': typeof DownloadsJobIdRoute
  '/library/$mangaId': typeof LibraryMangaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRouteWithChildren
  '/downloads': typeof DownloadsRouteWithChildren
  '/follows': typeof FollowsRoute
  '/library': typeof LibraryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/browse/$key': typeof BrowseKeyRoute
  '/downloads/$jobId': typeof DownloadsJobIdRoute
  '/library/$mangaId': typeof LibraryMangaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRouteWithChildren
  '/downloads': typeof DownloadsRouteWithChildren
  '/follows': typeof FollowsRoute
  '/library': typeof LibraryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/browse/$key': typeof BrowseKeyRoute
  '/downloads/$jobId': typeof DownloadsJobIdRoute
  '/library/$mangaId': typeof LibraryMangaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/downloads'
    | '/follows'
    | '/library'
    | '/settings'
    | '/browse/$key'
    | '/downloads/$jobId'
    | '/library/$mangaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/downloads'
    | '/follows'
    | '/library'
    | '/settings'
    | '/browse/$key'
    | '/downloads/$jobId'
    | '/library/$mangaId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/downloads'
    | '/follows'
    | '/library'
    | '/settings'
    | '/browse/$key'
    | '/downloads/$jobId'
    | '/library/$mangaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRouteWithChildren
  DownloadsRoute: typeof DownloadsRouteWithChildren
  FollowsRoute: typeof FollowsRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follows': {
      id: '/follows'
      path: '/follows'
      fullPath: '/follows'
      preLoaderRoute: typeof FollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$key': {
      id: '/browse/$key'
      path: '/$key'
      fullPath: '/browse/$key'
      preLoaderRoute: typeof BrowseKeyRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/downloads/$jobId': {
      id: '/downloads/$jobId'
      path: '/$jobId'
      fullPath: '/downloads/$jobId'
      preLoaderRoute: typeof DownloadsJobIdRouteImport
      parentRoute: typeof DownloadsRoute
    }
    '/library/$mangaId': {
      id: '/library/$mangaId'
      path: '/$mangaId'
      fullPath: '/library/$mangaId'
      preLoaderRoute: typeof LibraryMangaIdRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface BrowseRouteChildren {
  BrowseKeyRoute: typeof BrowseKeyRoute
}

const BrowseRouteChildren: BrowseRouteChildren = {
  BrowseKeyRoute: BrowseKeyRoute,
}

const BrowseRouteWithChildren =
  BrowseRoute._addFileChildren(BrowseRouteChildren)

interface DownloadsRouteChildren {
  DownloadsJobIdRoute: typeof DownloadsJobIdRoute
}

const DownloadsRouteChildren: DownloadsRouteChildren = {
  DownloadsJobIdRoute: DownloadsJobIdRoute,
}

const DownloadsRouteWithChildren = DownloadsRoute._addFileChildren(
  DownloadsRouteChildren,
)

interface LibraryRouteChildren {
  LibraryMangaIdRoute: typeof LibraryMangaIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryMangaIdRoute: LibraryMangaIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRouteWithChildren,
  DownloadsRoute: DownloadsRouteWithChildren,
  FollowsRoute: FollowsRoute,
  LibraryRoute: LibraryRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
